import type { BRepBuilderAPI_PipeError, BRepOffsetAPI_MakePipeShell, TopoDS_Shape, TopoDS_Vertex, TopoDS_Wire } from "ocjs-fluidcad";
import { getOC } from "../init.js";
import { Convert } from "../convert.js";
import type { SpineTrihedron } from "./spine-analysis.js";
import { resolveSweepTolerances, type SweepTolerancePolicy } from "./tolerances.js";
import type { Matrix4 } from "../../math/matrix4.js";
import type { Point } from "../../math/point.js";
import { boundedHelixSpine } from "./helix-spans.js";
import { Explorer } from "../explorer.js";
import { EdgeOps } from "../edge-ops.js";
import { ShapeOps } from "../shape-ops.js";
import { requireValidSolid } from "../solid-validation.js";
import type { ResolvedHelixGeometry } from "../../math/helix-geometry.js";

/** One MakePipeShell result: the pipe and the section faces at its two ends. */
export interface PipeRunResult {
  solid: TopoDS_Shape;
  firstFace: TopoDS_Shape;
  lastFace: TopoDS_Shape;
  /** One entry per fitted run; joining runs does not certify join accuracy. */
  diagnostics: PipeRunDiagnostics[];
  /** All spans generated by each original profile edge, before placement. */
  generatedFaces?: { profileMidpoint: Point; faces: TopoDS_Shape[] }[];
}

export interface PipeRunDiagnostics {
  transport: SpineTrihedron["kind"];
  placement: "atStart" | "atVertex" | "placed" | "automatic";
  withCorrection: boolean;
  tolerances: SweepTolerancePolicy;
  status: BRepBuilderAPI_PipeError;
  /** OCCT's maximum surface approximation error, in the document unit. */
  surfaceError: number | null;
  profileBounds: ReturnType<typeof ShapeOps.getBoundingBoxRaw>;
  spineBounds: ReturnType<typeof ShapeOps.getBoundingBoxRaw>;
  helix?: { startRadius: number; endRadius: number; height: number; turns: number };
}

export class SweepBuildError extends Error {
  constructor(readonly stage: "build" | "surfaceFit" | "solid", readonly diagnostics: PipeRunDiagnostics, reason: string) {
    super(`Sweep ${stage} failed: ${reason} (${diagnostics.status}; transport=${diagnostics.transport}; ` +
      `placement=${diagnostics.placement}; withCorrection=${diagnostics.withCorrection}; surfaceError=${diagnostics.surfaceError}; ` +
      `tolerance=${diagnostics.tolerances.linear3d} ${diagnostics.tolerances.unit}; ` +
      `boundary=${diagnostics.tolerances.boundary}; angular=${diagnostics.tolerances.angular} rad; ` +
      `maxSegments=${diagnostics.tolerances.maxSegments}; profileBounds=${JSON.stringify(diagnostics.profileBounds)}` +
      `; spineBounds=${JSON.stringify(diagnostics.spineBounds)}` +
      `${diagnostics.helix ? `; helix=${JSON.stringify(diagnostics.helix)}` : ""}).`);
    this.name = "SweepBuildError";
  }
}

/**
 * The section to carry along a run. A `placed` section already sits on the
 * selected station and is used as-is; an unplaced one is the
 * user's profile, which OCC may rotate square to the spine (`withCorrection`).
 */
export interface PipeSection {
  wire: TopoDS_Wire;
  placed: boolean;
  withCorrection: boolean;
  /** Explicit station, independent of the profile's offset from the path. */
  location?: TopoDS_Vertex;
  atStart?: boolean;
  transform?: Matrix4;
}

/** Sweeps one section along one G1 spine with `BRepOffsetAPI_MakePipeShell`. */
export class PipeRun {
  static sweep(
    spine: TopoDS_Wire,
    section: PipeSection,
    trihedron: SpineTrihedron,
    tolerances = resolveSweepTolerances(),
    helixGeometry?: ResolvedHelixGeometry,
  ): PipeRunResult {
    const geometry = helixGeometry ?? (trihedron.kind === "helix" ? trihedron.geometry : undefined);
    return PipeRun.withBuilder(spine, section, trihedron, (pipe, profileImage) => {
      const oc = getOC();
      const diagnostics: PipeRunDiagnostics = {
        transport: trihedron.kind,
        placement: section.atStart ? "atStart" : section.location ? "atVertex" : section.placed ? "placed" : "automatic",
        withCorrection: !section.placed && section.withCorrection,
        tolerances, status: pipe.GetStatus(), surfaceError: null,
        profileBounds: ShapeOps.getBoundingBoxRaw(section.wire),
        spineBounds: ShapeOps.getBoundingBoxRaw(spine),
        helix: geometry ? {
          startRadius: geometry.startRadius, endRadius: geometry.endRadius,
          height: geometry.zEnd - geometry.zStart, turns: geometry.turns,
        } : undefined,
      };
      const progress = new oc.Message_ProgressRange();
      try {
        pipe.Build(progress);
      } catch (cause) {
        diagnostics.status = pipe.GetStatus();
        throw new SweepBuildError("build", diagnostics, String(cause));
      } finally {
        progress.delete();
      }
      diagnostics.status = pipe.GetStatus();
      if (!pipe.IsDone() || diagnostics.status !== oc.BRepBuilderAPI_PipeError.BRepBuilderAPI_PipeDone) {
        throw new SweepBuildError("build", diagnostics, "kernel did not complete the pipe");
      }
      // BRepFill_Sweep reports the maximum GeomFill_Sweep surface fit error
      // across section/path spans. It is a length, not a roll or topology test.
      diagnostics.surfaceError = pipe.ErrorOnSurface();
      if (!Number.isFinite(diagnostics.surfaceError) || diagnostics.surfaceError < 0 ||
        diagnostics.surfaceError > tolerances.linear3d) {
        throw new SweepBuildError("surfaceFit", diagnostics, "reported surface error exceeds the physical fit budget");
      }
      let madeSolid: boolean;
      try {
        madeSolid = pipe.MakeSolid();
      } catch (cause) {
        throw new SweepBuildError("solid", diagnostics, String(cause));
      }
      if (!madeSolid) {
        throw new SweepBuildError("solid", diagnostics, "kernel did not produce a solid");
      }
      const solid = pipe.Shape();
      const generatedFaces: NonNullable<PipeRunResult["generatedFaces"]> = [];
      let firstFace: TopoDS_Shape | undefined;
      let lastFace: TopoDS_Shape | undefined;
      try {
        requireValidSolid(solid, "Sweep cutter", 1);
        if (geometry) {
          const edges = Explorer.findShapes(section.wire, oc.TopAbs_ShapeEnum.TopAbs_EDGE);
          try {
            for (const raw of edges) {
              const edge = oc.TopoDS.Edge(raw);
              try {
                const image = profileImage(edge);
                try {
                  generatedFaces.push({ profileMidpoint: EdgeOps.getEdgeMidPointRaw(edge),
                    faces: ShapeOps.shapeListToArray(pipe.Generated(image)) });
                } finally { image.delete(); }
              } finally { edge.delete(); }
            }
          } finally { edges.forEach(edge => edge.delete()); }
        }
        firstFace = pipe.FirstShape();
        lastFace = pipe.LastShape();
        return { solid, firstFace, lastFace, generatedFaces, diagnostics: [diagnostics] };
      } catch (error) {
        solid.delete(); firstFace?.delete(); lastFace?.delete();
        generatedFaces.forEach(entry => entry.faces.forEach(face => face.delete()));
        throw error;
      }
    }, tolerances, geometry);
  }

  /**
   * One configuration for production building and diagnostic section sampling.
   * The callback borrows the builder; it is always deleted before returning.
   * Use separate calls for Simulate and Build: the installed kernel fails when
   * both run on the same builder (see the subtractive sweep research plan).
   */
  static withBuilder<T>(
    spine: TopoDS_Wire,
    section: PipeSection,
    trihedron: SpineTrihedron,
    run: (pipe: BRepOffsetAPI_MakePipeShell, profileImage: (edge: TopoDS_Shape) => TopoDS_Shape) => T,
    tolerances: SweepTolerancePolicy = resolveSweepTolerances(),
    helixGeometry?: ResolvedHelixGeometry,
  ): T {
    const oc = getOC();
    const geometry = helixGeometry ?? (trihedron.kind === "helix" ? trihedron.geometry : undefined);
    // Construction follows path provenance, not transport. Tapers use the
    // existing binormal law but need bounded faces too. Forty-five-degree
    // patches reduce the native check's cost on the cut cone; whole-turn
    // patches fix its boolean but leave much slower interference checks.
    const tapered = geometry && geometry.startRadius !== geometry.endRadius;
    const boundedSpine = geometry ? boundedHelixSpine(spine,
      tapered ? Math.PI / 4 : 2 * Math.PI, !!tapered) : spine;
    let pipe: BRepOffsetAPI_MakePipeShell | undefined;
    const disposers: (() => void)[] = [];
    try {
      pipe = new oc.BRepOffsetAPI_MakePipeShell(boundedSpine);
      if (trihedron.kind === "binormal" || trihedron.kind === "helix") {
        const [binormalDir, dispose] = Convert.toGpDir(trihedron.kind === "helix" ? trihedron.geometry.frame.mainDirection : trihedron.axis);
        disposers.push(dispose);
        pipe.SetMode(binormalDir);
      } else {
        // Set every mode deliberately. OCCT's default is corrected Frenet;
        // true Frenet is an explicit comparator, not the general fallback.
        pipe.SetMode(trihedron.kind === "frenet");
      }
      // The audited OCCT sources default to 100 spans; some helical surfaces
      // need more. The ceiling limits the adaptive fit, not its accuracy.
      pipe.SetMaxSegments(tolerances.maxSegments);
      pipe.SetTolerance(tolerances.linear3d, tolerances.boundary, tolerances.angular);
      // The spine handed in is G1 by construction (SpineAnalysis splits it at
      // corners), so OCCT's default transition — which would carry the frame
      // across a corner unturned and flatten the section — never triggers.
      const correction = section.placed ? false : section.withCorrection;
      let wire = section.wire;
      let profileImage = (edge: TopoDS_Shape) => edge.Oriented(edge.Orientation());
      if (section.transform) {
        const [trsf, dispose] = Convert.toGpTrsf(section.transform);
        disposers.push(dispose);
        const transform = new oc.BRepBuilderAPI_Transform(wire, trsf, true);
        profileImage = edge => transform.ModifiedShape(edge);
        disposers.push(() => transform.delete());
        wire = oc.TopoDS.Wire(transform.Shape());
        disposers.push(() => wire.delete());
      }
      let location = section.location;
      if (section.atStart) {
        const explorer = new oc.BRepTools_WireExplorer(boundedSpine);
        const edge = explorer.Current();
        location = oc.TopExp.FirstVertex(edge, true);
        edge.delete(); explorer.delete();
        const vertex = location;
        disposers.push(() => vertex.delete());
      }
      if (location) {
        pipe.Add(wire, location, false, correction);
      } else {
        pipe.Add(wire, false, correction);
      }
      return run(pipe, profileImage);
    } finally {
      pipe?.delete();
      disposers.reverse().forEach(dispose => dispose());
      if (boundedSpine !== spine) boundedSpine.delete();
    }
  }
}
