import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Section order is fixed here; page order inside a section comes from each
// page's `sidebar_position` and each sub-folder's `_category_.json`.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'installation',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'generated-index', slug: 'getting-started', description: 'Design a part, give it connectors, export it, then insert it into an assembly and drive a joint — one small project, start to finish.'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Datums',
      link: {type: 'generated-index', slug: 'datums', description: 'Reference axes and planes: the construction geometry sketches, revolves and patterns are built on.'},
      items: [{type: 'autogenerated', dirName: 'datums'}],
    },
    {
      type: 'category',
      label: 'Sketching',
      link: {type: 'generated-index', slug: 'sketching', description: 'Draw on a plane or a face, then let constraints pin the drawing down.'},
      items: [{type: 'autogenerated', dirName: 'sketching'}],
    },
    {
      type: 'category',
      label: '3D Operations',
      link: {type: 'generated-index', slug: '3d-operations', description: 'Turn sketches into solids and reshape them: extrude, revolve, sweep, loft, shell, fillet, chamfer, wrap, rib and helix.'},
      items: [{type: 'autogenerated', dirName: '3d-operations'}],
    },
    {
      type: 'category',
      label: 'Boolean Operations',
      link: {type: 'generated-index', slug: 'booleans', description: 'Fuse, common and subtract — the explicit booleans behind auto-fusion.'},
      items: [{type: 'autogenerated', dirName: 'booleans'}],
    },
    {
      type: 'category',
      label: 'Transforms',
      link: {type: 'generated-index', slug: 'transforms', description: 'Move, rotate and mirror solids.'},
      items: [{type: 'autogenerated', dirName: 'transforms'}],
    },
    {
      type: 'category',
      label: 'Patterns',
      link: {type: 'generated-index', slug: 'patterns', description: 'Copy finished shapes or repeat a feature along an axis, around an axis, or across a plane.'},
      items: [{type: 'autogenerated', dirName: 'patterns'}],
    },
    {
      type: 'category',
      label: 'Appearance',
      link: {type: 'generated-index', slug: 'appearance', description: 'Color faces and bodies.'},
      items: [{type: 'autogenerated', dirName: 'appearance'}],
    },
    {
      type: 'category',
      label: 'Extra',
      link: {type: 'generated-index', slug: 'extra', description: 'Reusable objects, units, project configuration and editor integrations.'},
      items: [{type: 'autogenerated', dirName: 'extra'}],
    },
    {
      type: 'category',
      label: 'Import & Export',
      link: {type: 'generated-index', slug: 'import-export', description: 'Bring STEP files in, write STEP, STL and PNG out.'},
      items: [{type: 'autogenerated', dirName: 'import-export'}],
    },
    {
      type: 'category',
      label: 'Part',
      link: {type: 'generated-index', slug: 'part', description: 'Part containers, parameters, connectors and exposed geometry — what makes a part insertable into an assembly.'},
      items: [{type: 'autogenerated', dirName: 'part'}],
    },
    {
      type: 'category',
      label: 'Assembly',
      link: {type: 'generated-index', slug: 'assembly', description: 'Insert parts, ground one, and connect the rest with joints.'},
      items: [{type: 'autogenerated', dirName: 'assembly'}],
    },
    'user-interface',
    'cli',
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'tutorials/index',
      },
      items: ['tutorials/lantern', 'tutorials/ice-cube-tray', 'tutorials/upper-alignment-clamp', 'tutorials/gear-housing', 'tutorials/cswp-sample-exam', 'tutorials/grooved-box', 'tutorials/flange-with-notch', 'tutorials/hinge-bracket', 'tutorials/l-stub', 'tutorials/drafted-box', 'tutorials/desk-organizer', 'tutorials/fork', 'tutorials/custom-elbow'],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
